[build]
  # Use the "dist" directory as the publish directory
  publish = "dist"

  # Build command for Vite
  command = "npm run build"

[[redirects]]
  # Redirect all routes to index.html for SPAs
  from = "/*"
  to = "/index.html"
  status = 200

# Explicit redirect for signin page
[[redirects]]
  from = "/signin"
  to = "/signin.html"
  status = 301

# Explicit redirect for all other HTML pages
[[redirects]]
  from = "/:page"
  to = "/:page.html"
  status = 301
  conditions = {Key = "query", Pattern = ""}

[[headers]]
  # Set CORS headers for JSON routes
  for = "/json/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Content-Type = "application/json"