[build]
  publish = "dist"
  command = "npm run build"

# Specific HTML page redirects (must come FIRST)
[[redirects]]
  from = "/signin"
  to = "/signin.html"
  status = 301

[[redirects]]
  from = "/forgot-password"
  to = "/forgot-password.html"
  status = 301

[[redirects]]
  from = "/reset-password"
  to = "/reset-password.html"
  status = 301

# Generic HTML redirect (for all other .html pages)
[[redirects]]
  from = "/:page"
  to = "/:page.html"
  status = 301
  conditions = {Key = "path", Pattern = "/([^.]+)"}  # Only match paths without dots

# SPA fallback (must come LAST)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/json/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Content-Type = "application/json"